### PR TITLE
Removed unnecessary regex files. Changed references to strings.

### PR DESCRIPTION
**Pull request by ATweedMITRE**
Certain regex files were created to satisfy MUST requirements and are no
longer needed as they can better be handled with the validator. The
references to these files were changed to strings.

### CODE REVIEW

**Comment by gtback** [comment]
Can we do some type of validation in the schemas (min/max length, or allowable characters)? For example, country code must be two lower-case letters, character sets can only be alphanumeric plus `-` and `_` (maybe, I'm not sure if that's correct), etc.

**Comment by ATweedMITRE** [comment]
Oh yeah definitely, I can just do a pattern within the property that calls for it. I'll add that in before I push the RC4 updated schemas out.

**Comment by gtback** [comment]
Sounds good, thanks, @ATweedMITRE . Do you want to do that in this PR, or do you want me to merge this and then start a new PR?

**Comment by ATweedMITRE** [comment]
You're welcome to merge that one and I'll start a new one.

**Comment by gtback** [comment]
Looks good to me!

**Pull request merged**
